sudo: false
before_script:
- echo "extension = <extension>.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- composer self
- composer --version
- composer install -n
language: php
php:
  - '7.2'
script:
 - vendor/bin/codecept run unit